#pragma once
#include <nlohmann/json.hpp>
#include <stdint.h>


namespace DeadFrame2D::Models
{
	enum class KeyboardKeyCode : uint16_t
	{
		UNKNOWN = 0,

		// Letters
		A, B, C, D, E, F, G, H, I, J,
		K, L, M, N, O, P, Q, R, S, T,
		U, V, W, X, Y, Z,

		// Numbers (top row)
		NUM_0,
		NUM_1,
		NUM_2,
		NUM_3,
		NUM_4,
		NUM_5,
		NUM_6,
		NUM_7,
		NUM_8,
		NUM_9,

		// Main keys
		ENTER,
		ESCAPE,
		BACKSPACE,
		TAB,
		SPACE,

		MINUS,
		EQUALS,
		LEFT_BRACKET,
		RIGHT_BRACKET,
		BACKSLASH,
		SEMICOLON,
		APOSTROPHE,
		GRAVE,
		COMMA,
		PERIOD,
		SLASH,

		CAPS_LOCK,

		// Function keys
		F1, F2, F3, F4, F5, F6,
		F7, F8, F9, F10, F11, F12,
		F13, F14, F15, F16, F17, F18,
		F19, F20, F21, F22, F23, F24,

		// Navigation
		PRINT_SCREEN,
		SCROLL_LOCK,
		PAUSE,
		INSERT,
		HOME,
		PAGE_UP,
		DELETE,
		END,
		PAGE_DOWN,
		RIGHT,
		LEFT,
		DOWN,
		UP,

		// Numpad
		NUM_LOCK,
		KP_DIVIDE,
		KP_MULTIPLY,
		KP_MINUS,
		KP_PLUS,
		KP_ENTER,
		KP_0,
		KP_1,
		KP_2,
		KP_3,
		KP_4,
		KP_5,
		KP_6,
		KP_7,
		KP_8,
		KP_9,
		KP_PERIOD,

		// Modifiers
		LCTRL,
		LSHIFT,
		LALT,
		LGUI,
		RCTRL,
		RSHIFT,
		RALT,
		RGUI,

		// Media / system
		VOLUME_UP,
		VOLUME_DOWN,
		MUTE,
		MEDIA_PLAY,
		MEDIA_STOP,
		MEDIA_NEXT,
		MEDIA_PREV,

		// Application
		APPLICATION, /**< windows contextual menu, compose */
		POWER, /**< The USB document says this is a status flag, not a physical key - but some Mac keyboards do have a power key. */
		SLEEP,

		COUNT_MAX
	};


	NLOHMANN_JSON_SERIALIZE_ENUM(KeyboardKeyCode,
	{
		{ KeyboardKeyCode::A, "A"},
		{ KeyboardKeyCode::B, "B"},
		{ KeyboardKeyCode::C, "C"},
		{ KeyboardKeyCode::D, "D"},
		{ KeyboardKeyCode::E, "E"},
		{ KeyboardKeyCode::F, "F"},
		{ KeyboardKeyCode::G, "G"},
		{ KeyboardKeyCode::H, "H"},
		{ KeyboardKeyCode::I, "I"},
		{ KeyboardKeyCode::J, "J"},
		{ KeyboardKeyCode::K, "K"},
		{ KeyboardKeyCode::L, "L"},
		{ KeyboardKeyCode::M, "M"},
		{ KeyboardKeyCode::N, "N"},
		{ KeyboardKeyCode::O, "O"},
		{ KeyboardKeyCode::P, "P"},
		{ KeyboardKeyCode::Q, "Q"},
		{ KeyboardKeyCode::R, "R"},
		{ KeyboardKeyCode::S, "S"},
		{ KeyboardKeyCode::T, "T"},
		{ KeyboardKeyCode::U, "U"},
		{ KeyboardKeyCode::V, "V"},
		{ KeyboardKeyCode::W, "W"},
		{ KeyboardKeyCode::X, "X"},
		{ KeyboardKeyCode::Y, "Y"},
		{ KeyboardKeyCode::Z, "Z"},

		{ KeyboardKeyCode::NUM_0, "Num0"},
		{ KeyboardKeyCode::NUM_1, "Num1"},
		{ KeyboardKeyCode::NUM_2, "Num2"},
		{ KeyboardKeyCode::NUM_3, "Num3"},
		{ KeyboardKeyCode::NUM_4, "Num4"},
		{ KeyboardKeyCode::NUM_5, "Num5"},
		{ KeyboardKeyCode::NUM_6, "Num6"},
		{ KeyboardKeyCode::NUM_7, "Num7"},
		{ KeyboardKeyCode::NUM_8, "Num8"},
		{ KeyboardKeyCode::NUM_9, "Num9"},

		{ KeyboardKeyCode::ENTER, "Enter"},
		{ KeyboardKeyCode::ESCAPE, "Escape"},
		{ KeyboardKeyCode::BACKSPACE, "Backspace"},
		{ KeyboardKeyCode::TAB, "Tab"},
		{ KeyboardKeyCode::SPACE, "Space"},

		{ KeyboardKeyCode::MINUS, "Minus"},
		{ KeyboardKeyCode::EQUALS, "Equals"},
		{ KeyboardKeyCode::LEFT_BRACKET, "LeftBracket"},
		{ KeyboardKeyCode::RIGHT_BRACKET, "RightBracket"},
		{ KeyboardKeyCode::BACKSLASH, "Backslash"},
		{ KeyboardKeyCode::SEMICOLON, "Semicolon"},
		{ KeyboardKeyCode::APOSTROPHE, "Apostrophe"},
		{ KeyboardKeyCode::GRAVE, "Grave"},
		{ KeyboardKeyCode::COMMA, "Comma"},
		{ KeyboardKeyCode::PERIOD, "Period"},
		{ KeyboardKeyCode::SLASH, "Slash"},

		{ KeyboardKeyCode::CAPS_LOCK, "CapsLock"},

		{ KeyboardKeyCode::F1, "F1"},
		{ KeyboardKeyCode::F2, "F2"},
		{ KeyboardKeyCode::F3, "F3"},
		{ KeyboardKeyCode::F4, "F4"},
		{ KeyboardKeyCode::F5, "F5"},
		{ KeyboardKeyCode::F6, "F6"},
		{ KeyboardKeyCode::F7, "F7"},
		{ KeyboardKeyCode::F8, "F8"},
		{ KeyboardKeyCode::F9, "F9"},
		{ KeyboardKeyCode::F10, "F10"},
		{ KeyboardKeyCode::F11, "F11"},
		{ KeyboardKeyCode::F12, "F12"},
		{ KeyboardKeyCode::F13, "F13"},
		{ KeyboardKeyCode::F14, "F14"},
		{ KeyboardKeyCode::F15, "F15"},
		{ KeyboardKeyCode::F16, "F16"},
		{ KeyboardKeyCode::F17, "F17"},
		{ KeyboardKeyCode::F18, "F18"},
		{ KeyboardKeyCode::F19, "F19"},
		{ KeyboardKeyCode::F20, "F20"},
		{ KeyboardKeyCode::F21, "F21"},
		{ KeyboardKeyCode::F22, "F22"},
		{ KeyboardKeyCode::F23, "F23"},
		{ KeyboardKeyCode::F24, "F24"},

		{ KeyboardKeyCode::PRINT_SCREEN, "PrintScreen"},
		{ KeyboardKeyCode::SCROLL_LOCK, "ScrollLock"},
		{ KeyboardKeyCode::PAUSE, "Pause"},
		{ KeyboardKeyCode::INSERT, "Insert"},
		{ KeyboardKeyCode::HOME, "Home"},
		{ KeyboardKeyCode::PAGE_UP, "PageUp"},
		{ KeyboardKeyCode::DELETE, "Delete"},
		{ KeyboardKeyCode::END, "End"},
		{ KeyboardKeyCode::PAGE_DOWN, "PageDown"},
		{ KeyboardKeyCode::RIGHT, "Right"},
		{ KeyboardKeyCode::LEFT, "Left"},
		{ KeyboardKeyCode::DOWN, "Down"},
		{ KeyboardKeyCode::UP, "Up"},

		{ KeyboardKeyCode::NUM_LOCK, "NumLock"},
		{ KeyboardKeyCode::KP_DIVIDE, "KpDivide"},
		{ KeyboardKeyCode::KP_MULTIPLY, "KpMultiply"},
		{ KeyboardKeyCode::KP_MINUS, "KpMinus"},
		{ KeyboardKeyCode::KP_PLUS, "KpPlus"},
		{ KeyboardKeyCode::KP_ENTER, "KpEnter"},
		{ KeyboardKeyCode::KP_0, "Kp0"},
		{ KeyboardKeyCode::KP_1, "Kp1"},
		{ KeyboardKeyCode::KP_2, "Kp2"},
		{ KeyboardKeyCode::KP_3, "Kp3"},
		{ KeyboardKeyCode::KP_4, "Kp4"},
		{ KeyboardKeyCode::KP_5, "Kp5"},
		{ KeyboardKeyCode::KP_6, "Kp6"},
		{ KeyboardKeyCode::KP_7, "Kp7"},
		{ KeyboardKeyCode::KP_8, "Kp8"},
		{ KeyboardKeyCode::KP_9, "Kp9"},
		{ KeyboardKeyCode::KP_PERIOD, "KpPeriod"},

		{ KeyboardKeyCode::LCTRL, "LCtrl" },
		{ KeyboardKeyCode::LSHIFT, "LShift" },
		{ KeyboardKeyCode::LALT, "LAlt" },
		{ KeyboardKeyCode::LGUI, "LGui" },
		{ KeyboardKeyCode::RCTRL, "RCtrl" },
		{ KeyboardKeyCode::RSHIFT, "RShift" },
		{ KeyboardKeyCode::RALT, "RAlt" },
		{ KeyboardKeyCode::RGUI, "RGui"},

		{ KeyboardKeyCode::VOLUME_UP, "VolumeUp" },
		{ KeyboardKeyCode::VOLUME_DOWN, "VolumeDown" },
		{ KeyboardKeyCode::MUTE, "Mute" },
		{ KeyboardKeyCode::MEDIA_PLAY, "MediaPlay" },
		{ KeyboardKeyCode::MEDIA_STOP, "MediaStop" },
		{ KeyboardKeyCode::MEDIA_NEXT, "MediaNext" },
		{ KeyboardKeyCode::MEDIA_PREV, "MediaPrev"},

		{ KeyboardKeyCode::APPLICATION, "Application" },
		{ KeyboardKeyCode::POWER, "Power" },
		{ KeyboardKeyCode::SLEEP, "Sleep"}
	});
}